### Day 3 – NumPy Basics for AIML

#### What I learned

- What NumPy is and why it is used in ML  
- Difference between Python lists and NumPy arrays  
- Array creation, indexing, and slicing  
- Vectorized operations without explicit loops  

#### What I implemented

- Created 1D and 2D NumPy arrays  
- Performed indexing and slicing operations  
- Applied element-wise mathematical operations  
- Compared Python loops with NumPy vector operations  

#### Observations

- NumPy code is cleaner and closer to mathematical notation  
- Vectorized operations are easier to read and less error-prone  
- NumPy makes numerical computation faster and more efficient  


In [3]:
import numpy as np

a = np.array([1,2,3,4,5], dtype='float32')
b = np.array([[12,14,16,18], [11,13,15,17]])
print(a)
print(b)
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)


[1. 2. 3. 4. 5.]
[[12 14 16 18]
 [11 13 15 17]]
(5,)
(2, 4)
float32
int64


In [13]:
import numpy as np

a = np.array([8,16,28,31,70,82,94,13])
print(a[0])
print(a[-1])
print(a[1:5])
b = np.array([[1,3,5,7,9],[2,4,6,8,0]])
print(b[0, :])
print(b[:, 2])


8
13
[16 28 31 70]
[1 3 5 7 9]
[5 6]


In [21]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
print(a + b)
print(a * 3)
print(a ** 2)


[2 2 4 4]
[ 3  6  9 12]
[ 1  4  9 16]


In [23]:
import numpy as np

#Squaring digits using python loop
num = [2,4,6,8,10]
squares = []
for i in num:
    squares.append(i ** 2)
print(squares)

#Squaring digits using numpy
num = np.array([2,4,6,8,10])
print(num ** 2)


[4, 16, 36, 64, 100]
[  4  16  36  64 100]


In [26]:
import numpy as np

a = np.array([[17,19,16,5],[25,50,20,1]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())


1
50
153
19.125
