### Day 4 – NumPy Advanced for AIML

#### What I learned

- How NumPy broadcasting works without explicit loops  
- Meaning of axis and how it controls row-wise and column-wise operations  
- Dot product as a fundamental operation in machine learning  
- Why NumPy is ideal for mathematical computations in ML  

#### What I implemented

- Broadcasting operations with scalars and arrays  
- Axis-based sum and mean calculations  
- Dot product between vectors and matrices  
- Feature scaling using NumPy operations  

#### Observations

- Broadcasting removes the need for manual looping  
- Axis logic is critical for correct data aggregation  
- Dot product connects NumPy directly to ML model computations  


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print("Original array:", arr)
print("After broadcasting (add 10):", result)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])
result = matrix + vector
print("Matrix:\n", matrix)
print("Vector:", vector)
print("After broadcasting:\n", result)

Original array: [1 2 3 4 5]
After broadcasting (add 10): [11 12 13 14 15]
Matrix:
 [[1 2 3]
 [4 5 6]]
Vector: [10 20 30]
After broadcasting:
 [[11 22 33]
 [14 25 36]]


In [2]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

sum_columns = np.sum(data, axis=0)
sum_rows = np.sum(data, axis=1)
print("Original matrix:\n", data)
print("Sum across columns (axis=0):", sum_columns)
print("Sum across rows (axis=1):", sum_rows)
mean_columns = np.mean(data, axis=0)
mean_rows = np.mean(data, axis=1)
print("Mean across columns (axis=0):", mean_columns)
print("Mean across rows (axis=1):", mean_rows)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum across columns (axis=0): [12 15 18]
Sum across rows (axis=1): [ 6 15 24]
Mean across columns (axis=0): [4. 5. 6.]
Mean across rows (axis=1): [2. 5. 8.]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Vector a:", a)
print("Vector b:", b)
print("Dot product:", dot_product)

matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

vector = np.array([10, 20])
result = np.dot(matrix, vector)
print("Shape of matrix:", matrix.shape)
print("Shape of vector:", vector.shape)
print("Matrix:\n", matrix)
print("Vector:", vector)
print("Matrix × Vector result:", result)

Vector a: [1 2 3]
Vector b: [4 5 6]
Dot product: 32
Shape of matrix: (3, 2)
Shape of vector: (2,)
Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Vector: [10 20]
Matrix × Vector result: [ 50 110 170]


In [8]:
values = np.array([10, 20, 30, 40, 50])
min_val = values.min()
max_val = values.max()
normalized = (values - min_val) / (max_val - min_val)
print("Original values:", values)
print("Normalized values:", normalized)

Original values: [10 20 30 40 50]
Normalized values: [0.   0.25 0.5  0.75 1.  ]
